-- ============================================================================
-- Create table: ys-addresses-country-data
-- Schema: public (develop.ys.spaces.postgis / railway)
-- Description: ISO 3166 country reference data for international address handling
-- ============================================================================

CREATE TABLE IF NOT EXISTS public."ys-addresses-country-data" (
    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name                  VARCHAR(256) NOT NULL,
    sovereignty           VARCHAR(100),
    alpha_2_code          CHAR(2) NOT NULL UNIQUE,
    alpha_3_code          CHAR(3) NOT NULL UNIQUE,
    numeric_code          CHAR(3) NOT NULL,
    subdivision_codes_link VARCHAR(20),
    tld                   VARCHAR(50),
    description           TEXT,
    is_active             BOOLEAN NOT NULL DEFAULT TRUE,
    meta_data             JSONB,
    created_by            UUID,
    updated_by            UUID,
    created_on            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_on            TIMESTAMPTZ
);

-- Indexes for common lookups
CREATE INDEX IF NOT EXISTS idx_country_data_alpha2 ON public."ys-addresses-country-data" (alpha_2_code);
CREATE INDEX IF NOT EXISTS idx_country_data_alpha3 ON public."ys-addresses-country-data" (alpha_3_code);
CREATE INDEX IF NOT EXISTS idx_country_data_numeric ON public."ys-addresses-country-data" (numeric_code);
CREATE INDEX IF NOT EXISTS idx_country_data_active ON public."ys-addresses-country-data" (is_active);

-- ============================================================================
-- Seed ISO 3166-1 country data
-- ============================================================================

INSERT INTO public."ys-addresses-country-data"
    (name, sovereignty, alpha_2_code, alpha_3_code, numeric_code, subdivision_codes_link, tld)
VALUES
    ('Afghanistan', 'UN member', 'AF', 'AFG', '004', 'ISO 3166-2:AF', '.af'),
    ('Åland Islands', 'Finland', 'AX', 'ALA', '248', 'ISO 3166-2:AX', '.ax'),
    ('Albania', 'UN member', 'AL', 'ALB', '008', 'ISO 3166-2:AL', '.al'),
    ('Algeria', 'UN member', 'DZ', 'DZA', '012', 'ISO 3166-2:DZ', '.dz'),
    ('American Samoa', 'United States', 'AS', 'ASM', '016', 'ISO 3166-2:AS', '.as'),
    ('Andorra', 'UN member', 'AD', 'AND', '020', 'ISO 3166-2:AD', '.ad'),
    ('Angola', 'UN member', 'AO', 'AGO', '024', 'ISO 3166-2:AO', '.ao'),
    ('Anguilla', 'United Kingdom', 'AI', 'AIA', '660', 'ISO 3166-2:AI', '.ai'),
    ('Antarctica', 'Antarctic Treaty', 'AQ', 'ATA', '010', 'ISO 3166-2:AQ', '.aq'),
    ('Antigua and Barbuda', 'UN member', 'AG', 'ATG', '028', 'ISO 3166-2:AG', '.ag'),
    ('Argentina', 'UN member', 'AR', 'ARG', '032', 'ISO 3166-2:AR', '.ar'),
    ('Armenia', 'UN member', 'AM', 'ARM', '051', 'ISO 3166-2:AM', '.am'),
    ('Aruba', 'Netherlands', 'AW', 'ABW', '533', 'ISO 3166-2:AW', '.aw'),
    ('Australia', 'UN member', 'AU', 'AUS', '036', 'ISO 3166-2:AU', '.au'),
    ('Austria', 'UN member', 'AT', 'AUT', '040', 'ISO 3166-2:AT', '.at'),
    ('Azerbaijan', 'UN member', 'AZ', 'AZE', '031', 'ISO 3166-2:AZ', '.az'),
    ('Bahamas (the)', 'UN member', 'BS', 'BHS', '044', 'ISO 3166-2:BS', '.bs'),
    ('Bahrain', 'UN member', 'BH', 'BHR', '048', 'ISO 3166-2:BH', '.bh'),
    ('Bangladesh', 'UN member', 'BD', 'BGD', '050', 'ISO 3166-2:BD', '.bd'),
    ('Barbados', 'UN member', 'BB', 'BRB', '052', 'ISO 3166-2:BB', '.bb'),
    ('Belarus', 'UN member', 'BY', 'BLR', '112', 'ISO 3166-2:BY', '.by'),
    ('Belgium', 'UN member', 'BE', 'BEL', '056', 'ISO 3166-2:BE', '.be'),
    ('Belize', 'UN member', 'BZ', 'BLZ', '084', 'ISO 3166-2:BZ', '.bz'),
    ('Benin', 'UN member', 'BJ', 'BEN', '204', 'ISO 3166-2:BJ', '.bj'),
    ('Bermuda', 'United Kingdom', 'BM', 'BMU', '060', 'ISO 3166-2:BM', '.bm'),
    ('Bhutan', 'UN member', 'BT', 'BTN', '064', 'ISO 3166-2:BT', '.bt'),
    ('Bolivia (Plurinational State of)', 'UN member', 'BO', 'BOL', '068', 'ISO 3166-2:BO', '.bo'),
    ('Bonaire, Sint Eustatius and Saba', 'Netherlands', 'BQ', 'BES', '535', 'ISO 3166-2:BQ', '.bq'),
    ('Bosnia and Herzegovina', 'UN member', 'BA', 'BIH', '070', 'ISO 3166-2:BA', '.ba'),
    ('Botswana', 'UN member', 'BW', 'BWA', '072', 'ISO 3166-2:BW', '.bw'),
    ('Bouvet Island', 'Norway', 'BV', 'BVT', '074', 'ISO 3166-2:BV', NULL),
    ('Brazil', 'UN member', 'BR', 'BRA', '076', 'ISO 3166-2:BR', '.br'),
    ('British Indian Ocean Territory (the)', 'United Kingdom', 'IO', 'IOT', '086', 'ISO 3166-2:IO', '.io'),
    ('Brunei Darussalam', 'UN member', 'BN', 'BRN', '096', 'ISO 3166-2:BN', '.bn'),
    ('Bulgaria', 'UN member', 'BG', 'BGR', '100', 'ISO 3166-2:BG', '.bg'),
    ('Burkina Faso', 'UN member', 'BF', 'BFA', '854', 'ISO 3166-2:BF', '.bf'),
    ('Burundi', 'UN member', 'BI', 'BDI', '108', 'ISO 3166-2:BI', '.bi'),
    ('Cabo Verde', 'UN member', 'CV', 'CPV', '132', 'ISO 3166-2:CV', '.cv'),
    ('Cambodia', 'UN member', 'KH', 'KHM', '116', 'ISO 3166-2:KH', '.kh'),
    ('Cameroon', 'UN member', 'CM', 'CMR', '120', 'ISO 3166-2:CM', '.cm'),
    ('Canada', 'UN member', 'CA', 'CAN', '124', 'ISO 3166-2:CA', '.ca'),
    ('Cayman Islands (the)', 'United Kingdom', 'KY', 'CYM', '136', 'ISO 3166-2:KY', '.ky'),
    ('Central African Republic (the)', 'UN member', 'CF', 'CAF', '140', 'ISO 3166-2:CF', '.cf'),
    ('Chad', 'UN member', 'TD', 'TCD', '148', 'ISO 3166-2:TD', '.td'),
    ('Chile', 'UN member', 'CL', 'CHL', '152', 'ISO 3166-2:CL', '.cl'),
    ('China', 'UN member', 'CN', 'CHN', '156', 'ISO 3166-2:CN', '.cn'),
    ('Christmas Island', 'Australia', 'CX', 'CXR', '162', 'ISO 3166-2:CX', '.cx'),
    ('Cocos (Keeling) Islands (the)', 'Australia', 'CC', 'CCK', '166', 'ISO 3166-2:CC', '.cc'),
    ('Colombia', 'UN member', 'CO', 'COL', '170', 'ISO 3166-2:CO', '.co'),
    ('Comoros (the)', 'UN member', 'KM', 'COM', '174', 'ISO 3166-2:KM', '.km'),
    ('Congo (the Democratic Republic of the)', 'UN member', 'CD', 'COD', '180', 'ISO 3166-2:CD', '.cd'),
    ('Congo (the)', 'UN member', 'CG', 'COG', '178', 'ISO 3166-2:CG', '.cg'),
    ('Cook Islands (the)', 'New Zealand', 'CK', 'COK', '184', 'ISO 3166-2:CK', '.ck'),
    ('Costa Rica', 'UN member', 'CR', 'CRI', '188', 'ISO 3166-2:CR', '.cr'),
    ('Côte d''Ivoire', 'UN member', 'CI', 'CIV', '384', 'ISO 3166-2:CI', '.ci'),
    ('Croatia', 'UN member', 'HR', 'HRV', '191', 'ISO 3166-2:HR', '.hr'),
    ('Cuba', 'UN member', 'CU', 'CUB', '192', 'ISO 3166-2:CU', '.cu'),
    ('Curaçao', 'Netherlands', 'CW', 'CUW', '531', 'ISO 3166-2:CW', '.cw'),
    ('Cyprus', 'UN member', 'CY', 'CYP', '196', 'ISO 3166-2:CY', '.cy'),
    ('Czechia', 'UN member', 'CZ', 'CZE', '203', 'ISO 3166-2:CZ', '.cz'),
    ('Denmark', 'UN member', 'DK', 'DNK', '208', 'ISO 3166-2:DK', '.dk'),
    ('Djibouti', 'UN member', 'DJ', 'DJI', '262', 'ISO 3166-2:DJ', '.dj'),
    ('Dominica', 'UN member', 'DM', 'DMA', '212', 'ISO 3166-2:DM', '.dm'),
    ('Dominican Republic (the)', 'UN member', 'DO', 'DOM', '214', 'ISO 3166-2:DO', '.do'),
    ('Ecuador', 'UN member', 'EC', 'ECU', '218', 'ISO 3166-2:EC', '.ec'),
    ('Egypt', 'UN member', 'EG', 'EGY', '818', 'ISO 3166-2:EG', '.eg'),
    ('El Salvador', 'UN member', 'SV', 'SLV', '222', 'ISO 3166-2:SV', '.sv'),
    ('Equatorial Guinea', 'UN member', 'GQ', 'GNQ', '226', 'ISO 3166-2:GQ', '.gq'),
    ('Eritrea', 'UN member', 'ER', 'ERI', '232', 'ISO 3166-2:ER', '.er'),
    ('Estonia', 'UN member', 'EE', 'EST', '233', 'ISO 3166-2:EE', '.ee'),
    ('Eswatini', 'UN member', 'SZ', 'SWZ', '748', 'ISO 3166-2:SZ', '.sz'),
    ('Ethiopia', 'UN member', 'ET', 'ETH', '231', 'ISO 3166-2:ET', '.et'),
    ('Falkland Islands (the) [Malvinas]', 'United Kingdom', 'FK', 'FLK', '238', 'ISO 3166-2:FK', '.fk'),
    ('Faroe Islands (the)', 'Denmark', 'FO', 'FRO', '234', 'ISO 3166-2:FO', '.fo'),
    ('Fiji', 'UN member', 'FJ', 'FJI', '242', 'ISO 3166-2:FJ', '.fj'),
    ('Finland', 'UN member', 'FI', 'FIN', '246', 'ISO 3166-2:FI', '.fi'),
    ('France', 'UN member', 'FR', 'FRA', '250', 'ISO 3166-2:FR', '.fr'),
    ('French Guiana', 'France', 'GF', 'GUF', '254', 'ISO 3166-2:GF', '.gf'),
    ('French Polynesia', 'France', 'PF', 'PYF', '258', 'ISO 3166-2:PF', '.pf'),
    ('French Southern Territories (the)', 'France', 'TF', 'ATF', '260', 'ISO 3166-2:TF', '.tf'),
    ('Gabon', 'UN member', 'GA', 'GAB', '266', 'ISO 3166-2:GA', '.ga'),
    ('Gambia (the)', 'UN member', 'GM', 'GMB', '270', 'ISO 3166-2:GM', '.gm'),
    ('Georgia', 'UN member', 'GE', 'GEO', '268', 'ISO 3166-2:GE', '.ge'),
    ('Germany', 'UN member', 'DE', 'DEU', '276', 'ISO 3166-2:DE', '.de'),
    ('Ghana', 'UN member', 'GH', 'GHA', '288', 'ISO 3166-2:GH', '.gh'),
    ('Gibraltar', 'United Kingdom', 'GI', 'GIB', '292', 'ISO 3166-2:GI', '.gi'),
    ('Greece', 'UN member', 'GR', 'GRC', '300', 'ISO 3166-2:GR', '.gr'),
    ('Greenland', 'Denmark', 'GL', 'GRL', '304', 'ISO 3166-2:GL', '.gl'),
    ('Grenada', 'UN member', 'GD', 'GRD', '308', 'ISO 3166-2:GD', '.gd'),
    ('Guadeloupe', 'France', 'GP', 'GLP', '312', 'ISO 3166-2:GP', '.gp'),
    ('Guam', 'United States', 'GU', 'GUM', '316', 'ISO 3166-2:GU', '.gu'),
    ('Guatemala', 'UN member', 'GT', 'GTM', '320', 'ISO 3166-2:GT', '.gt'),
    ('Guernsey', 'British Crown', 'GG', 'GGY', '831', 'ISO 3166-2:GG', '.gg'),
    ('Guinea', 'UN member', 'GN', 'GIN', '324', 'ISO 3166-2:GN', '.gn'),
    ('Guinea-Bissau', 'UN member', 'GW', 'GNB', '624', 'ISO 3166-2:GW', '.gw'),
    ('Guyana', 'UN member', 'GY', 'GUY', '328', 'ISO 3166-2:GY', '.gy'),
    ('Haiti', 'UN member', 'HT', 'HTI', '332', 'ISO 3166-2:HT', '.ht'),
    ('Heard Island and McDonald Islands', 'Australia', 'HM', 'HMD', '334', 'ISO 3166-2:HM', '.hm'),
    ('Holy See (the)', 'UN observer', 'VA', 'VAT', '336', 'ISO 3166-2:VA', '.va'),
    ('Honduras', 'UN member', 'HN', 'HND', '340', 'ISO 3166-2:HN', '.hn'),
    ('Hong Kong', 'China', 'HK', 'HKG', '344', 'ISO 3166-2:HK', '.hk'),
    ('Hungary', 'UN member', 'HU', 'HUN', '348', 'ISO 3166-2:HU', '.hu'),
    ('Iceland', 'UN member', 'IS', 'ISL', '352', 'ISO 3166-2:IS', '.is'),
    ('India', 'UN member', 'IN', 'IND', '356', 'ISO 3166-2:IN', '.in'),
    ('Indonesia', 'UN member', 'ID', 'IDN', '360', 'ISO 3166-2:ID', '.id'),
    ('Iran (Islamic Republic of)', 'UN member', 'IR', 'IRN', '364', 'ISO 3166-2:IR', '.ir'),
    ('Iraq', 'UN member', 'IQ', 'IRQ', '368', 'ISO 3166-2:IQ', '.iq'),
    ('Ireland', 'UN member', 'IE', 'IRL', '372', 'ISO 3166-2:IE', '.ie'),
    ('Isle of Man', 'British Crown', 'IM', 'IMN', '833', 'ISO 3166-2:IM', '.im'),
    ('Israel', 'UN member', 'IL', 'ISR', '376', 'ISO 3166-2:IL', '.il'),
    ('Italy', 'UN member', 'IT', 'ITA', '380', 'ISO 3166-2:IT', '.it'),
    ('Jamaica', 'UN member', 'JM', 'JAM', '388', 'ISO 3166-2:JM', '.jm'),
    ('Japan', 'UN member', 'JP', 'JPN', '392', 'ISO 3166-2:JP', '.jp'),
    ('Jersey', 'British Crown', 'JE', 'JEY', '832', 'ISO 3166-2:JE', '.je'),
    ('Jordan', 'UN member', 'JO', 'JOR', '400', 'ISO 3166-2:JO', '.jo'),
    ('Kazakhstan', 'UN member', 'KZ', 'KAZ', '398', 'ISO 3166-2:KZ', '.kz'),
    ('Kenya', 'UN member', 'KE', 'KEN', '404', 'ISO 3166-2:KE', '.ke'),
    ('Kiribati', 'UN member', 'KI', 'KIR', '296', 'ISO 3166-2:KI', '.ki'),
    ('Korea (the Democratic People''s Republic of)', 'UN member', 'KP', 'PRK', '408', 'ISO 3166-2:KP', '.kp'),
    ('Korea (the Republic of)', 'UN member', 'KR', 'KOR', '410', 'ISO 3166-2:KR', '.kr'),
    ('Kuwait', 'UN member', 'KW', 'KWT', '414', 'ISO 3166-2:KW', '.kw'),
    ('Kyrgyzstan', 'UN member', 'KG', 'KGZ', '417', 'ISO 3166-2:KG', '.kg'),
    ('Lao People''s Democratic Republic (the)', 'UN member', 'LA', 'LAO', '418', 'ISO 3166-2:LA', '.la'),
    ('Latvia', 'UN member', 'LV', 'LVA', '428', 'ISO 3166-2:LV', '.lv'),
    ('Lebanon', 'UN member', 'LB', 'LBN', '422', 'ISO 3166-2:LB', '.lb'),
    ('Lesotho', 'UN member', 'LS', 'LSO', '426', 'ISO 3166-2:LS', '.ls'),
    ('Liberia', 'UN member', 'LR', 'LBR', '430', 'ISO 3166-2:LR', '.lr'),
    ('Libya', 'UN member', 'LY', 'LBY', '434', 'ISO 3166-2:LY', '.ly'),
    ('Liechtenstein', 'UN member', 'LI', 'LIE', '438', 'ISO 3166-2:LI', '.li'),
    ('Lithuania', 'UN member', 'LT', 'LTU', '440', 'ISO 3166-2:LT', '.lt'),
    ('Luxembourg', 'UN member', 'LU', 'LUX', '442', 'ISO 3166-2:LU', '.lu'),
    ('Macao', 'China', 'MO', 'MAC', '446', 'ISO 3166-2:MO', '.mo'),
    ('Madagascar', 'UN member', 'MG', 'MDG', '450', 'ISO 3166-2:MG', '.mg'),
    ('Malawi', 'UN member', 'MW', 'MWI', '454', 'ISO 3166-2:MW', '.mw'),
    ('Malaysia', 'UN member', 'MY', 'MYS', '458', 'ISO 3166-2:MY', '.my'),
    ('Maldives', 'UN member', 'MV', 'MDV', '462', 'ISO 3166-2:MV', '.mv'),
    ('Mali', 'UN member', 'ML', 'MLI', '466', 'ISO 3166-2:ML', '.ml'),
    ('Malta', 'UN member', 'MT', 'MLT', '470', 'ISO 3166-2:MT', '.mt'),
    ('Marshall Islands (the)', 'UN member', 'MH', 'MHL', '584', 'ISO 3166-2:MH', '.mh'),
    ('Martinique', 'France', 'MQ', 'MTQ', '474', 'ISO 3166-2:MQ', '.mq'),
    ('Mauritania', 'UN member', 'MR', 'MRT', '478', 'ISO 3166-2:MR', '.mr'),
    ('Mauritius', 'UN member', 'MU', 'MUS', '480', 'ISO 3166-2:MU', '.mu'),
    ('Mayotte', 'France', 'YT', 'MYT', '175', 'ISO 3166-2:YT', '.yt'),
    ('Mexico', 'UN member', 'MX', 'MEX', '484', 'ISO 3166-2:MX', '.mx'),
    ('Micronesia (Federated States of)', 'UN member', 'FM', 'FSM', '583', 'ISO 3166-2:FM', '.fm'),
    ('Moldova (the Republic of)', 'UN member', 'MD', 'MDA', '498', 'ISO 3166-2:MD', '.md'),
    ('Monaco', 'UN member', 'MC', 'MCO', '492', 'ISO 3166-2:MC', '.mc'),
    ('Mongolia', 'UN member', 'MN', 'MNG', '496', 'ISO 3166-2:MN', '.mn'),
    ('Montenegro', 'UN member', 'ME', 'MNE', '499', 'ISO 3166-2:ME', '.me'),
    ('Montserrat', 'United Kingdom', 'MS', 'MSR', '500', 'ISO 3166-2:MS', '.ms'),
    ('Morocco', 'UN member', 'MA', 'MAR', '504', 'ISO 3166-2:MA', '.ma'),
    ('Mozambique', 'UN member', 'MZ', 'MOZ', '508', 'ISO 3166-2:MZ', '.mz'),
    ('Myanmar', 'UN member', 'MM', 'MMR', '104', 'ISO 3166-2:MM', '.mm'),
    ('Namibia', 'UN member', 'NA', 'NAM', '516', 'ISO 3166-2:NA', '.na'),
    ('Nauru', 'UN member', 'NR', 'NRU', '520', 'ISO 3166-2:NR', '.nr'),
    ('Nepal', 'UN member', 'NP', 'NPL', '524', 'ISO 3166-2:NP', '.np'),
    ('Netherlands (Kingdom of the)', 'UN member', 'NL', 'NLD', '528', 'ISO 3166-2:NL', '.nl'),
    ('New Caledonia', 'France', 'NC', 'NCL', '540', 'ISO 3166-2:NC', '.nc'),
    ('New Zealand', 'UN member', 'NZ', 'NZL', '554', 'ISO 3166-2:NZ', '.nz'),
    ('Nicaragua', 'UN member', 'NI', 'NIC', '558', 'ISO 3166-2:NI', '.ni'),
    ('Niger (the)', 'UN member', 'NE', 'NER', '562', 'ISO 3166-2:NE', '.ne'),
    ('Nigeria', 'UN member', 'NG', 'NGA', '566', 'ISO 3166-2:NG', '.ng'),
    ('Niue', 'New Zealand', 'NU', 'NIU', '570', 'ISO 3166-2:NU', '.nu'),
    ('Norfolk Island', 'Australia', 'NF', 'NFK', '574', 'ISO 3166-2:NF', '.nf'),
    ('North Macedonia', 'UN member', 'MK', 'MKD', '807', 'ISO 3166-2:MK', '.mk'),
    ('Northern Mariana Islands (the)', 'United States', 'MP', 'MNP', '580', 'ISO 3166-2:MP', '.mp'),
    ('Norway', 'UN member', 'NO', 'NOR', '578', 'ISO 3166-2:NO', '.no'),
    ('Oman', 'UN member', 'OM', 'OMN', '512', 'ISO 3166-2:OM', '.om'),
    ('Pakistan', 'UN member', 'PK', 'PAK', '586', 'ISO 3166-2:PK', '.pk'),
    ('Palau', 'UN member', 'PW', 'PLW', '585', 'ISO 3166-2:PW', '.pw'),
    ('Palestine, State of', 'UN observer', 'PS', 'PSE', '275', 'ISO 3166-2:PS', '.ps'),
    ('Panama', 'UN member', 'PA', 'PAN', '591', 'ISO 3166-2:PA', '.pa'),
    ('Papua New Guinea', 'UN member', 'PG', 'PNG', '598', 'ISO 3166-2:PG', '.pg'),
    ('Paraguay', 'UN member', 'PY', 'PRY', '600', 'ISO 3166-2:PY', '.py'),
    ('Peru', 'UN member', 'PE', 'PER', '604', 'ISO 3166-2:PE', '.pe'),
    ('Philippines (the)', 'UN member', 'PH', 'PHL', '608', 'ISO 3166-2:PH', '.ph'),
    ('Pitcairn', 'United Kingdom', 'PN', 'PCN', '612', 'ISO 3166-2:PN', '.pn'),
    ('Poland', 'UN member', 'PL', 'POL', '616', 'ISO 3166-2:PL', '.pl'),
    ('Portugal', 'UN member', 'PT', 'PRT', '620', 'ISO 3166-2:PT', '.pt'),
    ('Puerto Rico', 'United States', 'PR', 'PRI', '630', 'ISO 3166-2:PR', '.pr'),
    ('Qatar', 'UN member', 'QA', 'QAT', '634', 'ISO 3166-2:QA', '.qa'),
    ('Réunion', 'France', 'RE', 'REU', '638', 'ISO 3166-2:RE', '.re'),
    ('Romania', 'UN member', 'RO', 'ROU', '642', 'ISO 3166-2:RO', '.ro'),
    ('Russian Federation (the)', 'UN member', 'RU', 'RUS', '643', 'ISO 3166-2:RU', '.ru'),
    ('Rwanda', 'UN member', 'RW', 'RWA', '646', 'ISO 3166-2:RW', '.rw'),
    ('Saint Barthélemy', 'France', 'BL', 'BLM', '652', 'ISO 3166-2:BL', '.bl'),
    ('Saint Helena, Ascension and Tristan da Cunha', 'United Kingdom', 'SH', 'SHN', '654', 'ISO 3166-2:SH', '.sh'),
    ('Saint Kitts and Nevis', 'UN member', 'KN', 'KNA', '659', 'ISO 3166-2:KN', '.kn'),
    ('Saint Lucia', 'UN member', 'LC', 'LCA', '662', 'ISO 3166-2:LC', '.lc'),
    ('Saint Martin (French part)', 'France', 'MF', 'MAF', '663', 'ISO 3166-2:MF', '.mf'),
    ('Saint Pierre and Miquelon', 'France', 'PM', 'SPM', '666', 'ISO 3166-2:PM', '.pm'),
    ('Saint Vincent and the Grenadines', 'UN member', 'VC', 'VCT', '670', 'ISO 3166-2:VC', '.vc'),
    ('Samoa', 'UN member', 'WS', 'WSM', '882', 'ISO 3166-2:WS', '.ws'),
    ('San Marino', 'UN member', 'SM', 'SMR', '674', 'ISO 3166-2:SM', '.sm'),
    ('Sao Tome and Principe', 'UN member', 'ST', 'STP', '678', 'ISO 3166-2:ST', '.st'),
    ('Saudi Arabia', 'UN member', 'SA', 'SAU', '682', 'ISO 3166-2:SA', '.sa'),
    ('Senegal', 'UN member', 'SN', 'SEN', '686', 'ISO 3166-2:SN', '.sn'),
    ('Serbia', 'UN member', 'RS', 'SRB', '688', 'ISO 3166-2:RS', '.rs'),
    ('Seychelles', 'UN member', 'SC', 'SYC', '690', 'ISO 3166-2:SC', '.sc'),
    ('Sierra Leone', 'UN member', 'SL', 'SLE', '694', 'ISO 3166-2:SL', '.sl'),
    ('Singapore', 'UN member', 'SG', 'SGP', '702', 'ISO 3166-2:SG', '.sg'),
    ('Sint Maarten (Dutch part)', 'Netherlands', 'SX', 'SXM', '534', 'ISO 3166-2:SX', '.sx'),
    ('Slovakia', 'UN member', 'SK', 'SVK', '703', 'ISO 3166-2:SK', '.sk'),
    ('Slovenia', 'UN member', 'SI', 'SVN', '705', 'ISO 3166-2:SI', '.si'),
    ('Solomon Islands', 'UN member', 'SB', 'SLB', '090', 'ISO 3166-2:SB', '.sb'),
    ('Somalia', 'UN member', 'SO', 'SOM', '706', 'ISO 3166-2:SO', '.so'),
    ('South Africa', 'UN member', 'ZA', 'ZAF', '710', 'ISO 3166-2:ZA', '.za'),
    ('South Georgia and the South Sandwich Islands', 'United Kingdom', 'GS', 'SGS', '239', 'ISO 3166-2:GS', '.gs'),
    ('South Sudan', 'UN member', 'SS', 'SSD', '728', 'ISO 3166-2:SS', '.ss'),
    ('Spain', 'UN member', 'ES', 'ESP', '724', 'ISO 3166-2:ES', '.es'),
    ('Sri Lanka', 'UN member', 'LK', 'LKA', '144', 'ISO 3166-2:LK', '.lk'),
    ('Sudan (the)', 'UN member', 'SD', 'SDN', '729', 'ISO 3166-2:SD', '.sd'),
    ('Suriname', 'UN member', 'SR', 'SUR', '740', 'ISO 3166-2:SR', '.sr'),
    ('Svalbard and Jan Mayen', 'Norway', 'SJ', 'SJM', '744', 'ISO 3166-2:SJ', NULL),
    ('Sweden', 'UN member', 'SE', 'SWE', '752', 'ISO 3166-2:SE', '.se'),
    ('Switzerland', 'UN member', 'CH', 'CHE', '756', 'ISO 3166-2:CH', '.ch'),
    ('Syrian Arab Republic (the)', 'UN member', 'SY', 'SYR', '760', 'ISO 3166-2:SY', '.sy'),
    ('Taiwan (Province of China)', 'Disputed', 'TW', 'TWN', '158', 'ISO 3166-2:TW', '.tw'),
    ('Tajikistan', 'UN member', 'TJ', 'TJK', '762', 'ISO 3166-2:TJ', '.tj'),
    ('Tanzania, the United Republic of', 'UN member', 'TZ', 'TZA', '834', 'ISO 3166-2:TZ', '.tz'),
    ('Thailand', 'UN member', 'TH', 'THA', '764', 'ISO 3166-2:TH', '.th'),
    ('Timor-Leste', 'UN member', 'TL', 'TLS', '626', 'ISO 3166-2:TL', '.tl'),
    ('Togo', 'UN member', 'TG', 'TGO', '768', 'ISO 3166-2:TG', '.tg'),
    ('Tokelau', 'New Zealand', 'TK', 'TKL', '772', 'ISO 3166-2:TK', '.tk'),
    ('Tonga', 'UN member', 'TO', 'TON', '776', 'ISO 3166-2:TO', '.to'),
    ('Trinidad and Tobago', 'UN member', 'TT', 'TTO', '780', 'ISO 3166-2:TT', '.tt'),
    ('Tunisia', 'UN member', 'TN', 'TUN', '788', 'ISO 3166-2:TN', '.tn'),
    ('Türkiye', 'UN member', 'TR', 'TUR', '792', 'ISO 3166-2:TR', '.tr'),
    ('Turkmenistan', 'UN member', 'TM', 'TKM', '795', 'ISO 3166-2:TM', '.tm'),
    ('Turks and Caicos Islands (the)', 'United Kingdom', 'TC', 'TCA', '796', 'ISO 3166-2:TC', '.tc'),
    ('Tuvalu', 'UN member', 'TV', 'TUV', '798', 'ISO 3166-2:TV', '.tv'),
    ('Uganda', 'UN member', 'UG', 'UGA', '800', 'ISO 3166-2:UG', '.ug'),
    ('Ukraine', 'UN member', 'UA', 'UKR', '804', 'ISO 3166-2:UA', '.ua'),
    ('United Arab Emirates (the)', 'UN member', 'AE', 'ARE', '784', 'ISO 3166-2:AE', '.ae'),
    ('United Kingdom of Great Britain and Northern Ireland (the)', 'UN member', 'GB', 'GBR', '826', 'ISO 3166-2:GB', '.gb,.uk'),
    ('United States Minor Outlying Islands (the)', 'United States', 'UM', 'UMI', '581', 'ISO 3166-2:UM', NULL),
    ('United States of America (the)', 'UN member', 'US', 'USA', '840', 'ISO 3166-2:US', '.us'),
    ('Uruguay', 'UN member', 'UY', 'URY', '858', 'ISO 3166-2:UY', '.uy'),
    ('Uzbekistan', 'UN member', 'UZ', 'UZB', '860', 'ISO 3166-2:UZ', '.uz'),
    ('Vanuatu', 'UN member', 'VU', 'VUT', '548', 'ISO 3166-2:VU', '.vu'),
    ('Venezuela (Bolivarian Republic of)', 'UN member', 'VE', 'VEN', '862', 'ISO 3166-2:VE', '.ve'),
    ('Viet Nam', 'UN member', 'VN', 'VNM', '704', 'ISO 3166-2:VN', '.vn'),
    ('Virgin Islands (British)', 'United Kingdom', 'VG', 'VGB', '092', 'ISO 3166-2:VG', '.vg'),
    ('Virgin Islands (U.S.)', 'United States', 'VI', 'VIR', '850', 'ISO 3166-2:VI', '.vi'),
    ('Wallis and Futuna', 'France', 'WF', 'WLF', '876', 'ISO 3166-2:WF', '.wf'),
    ('Western Sahara', 'Disputed', 'EH', 'ESH', '732', 'ISO 3166-2:EH', NULL),
    ('Yemen', 'UN member', 'YE', 'YEM', '887', 'ISO 3166-2:YE', '.ye'),
    ('Zambia', 'UN member', 'ZM', 'ZMB', '894', 'ISO 3166-2:ZM', '.zm'),
    ('Zimbabwe', 'UN member', 'ZW', 'ZWE', '716', 'ISO 3166-2:ZW', '.zw')
ON CONFLICT (alpha_2_code) DO NOTHING;
